name: CI - Test PostgreSQL DB

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: online_library_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get install -y postgresql-client

      - name: Apply schema.sql
        run: |
          PGPASSWORD=postgres psql \
            -h localhost -U postgres -d online_library_dev \
            -f sql/schema.sql

      - name: Apply sample_data.sql
        run: |
          PGPASSWORD=postgres psql \
            -h localhost -U postgres -d online_library_dev \
            -f sql/sample_data.sql

      - name: Run queries.sql
        run: |
          PGPASSWORD=postgres psql \
            -h localhost -U postgres -d online_library_dev \
            -f sql/queries.sql
